# Generated by Django 5.1.4 on 2025-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
