# Generated by Django 5.1.4 on 2025-01-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0002_payment_reservation_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='guest',
            field=models.TextField(null=True),
        ),
    ]
