# Generated by Django 5.1.4 on 2025-01-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0002_reservation_user_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
