# Generated by Django 5.1.4 on 2025-01-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0003_alter_reservation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paynow_id',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='redirect_url',
            field=models.TextField(null=True),
        ),
    ]
