# Generated by Django 5.1.4 on 2025-01-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0003_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='double_bed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='single_bed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single'), ('double', 'Double'), ('suite', 'Suite'), ('family', 'Family'), ('special', 'Special'), ('party', 'Party'), ('marriage', 'Marriage'), ('triple', 'Triple'), ('triple_marriage', 'Triple Marriage')], max_length=20),
        ),
    ]
